# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bluectl < Formula
  desc "CLI for managing BlueField DPUs via Secure Infrastructure"
  homepage "https://github.com/gobeyondidentity/secure-infra"
  version "0.6.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.7/bluectl_darwin_amd64.tar.gz"
      sha256 "c8b26ea250cb0cf82267062b437f035f75b6d7a5681fdd1e0fd6c0f9088a0d46"

      def install
        bin.install "bluectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.7/bluectl_darwin_arm64.tar.gz"
      sha256 "bf63047511764408a512dc09f903390ff18c4080db4d43026d5fb81ece23de06"

      def install
        bin.install "bluectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.7/bluectl_linux_amd64.tar.gz"
      sha256 "8e36ab4e3c437268bee8246b5a9c3f708628111be15a995f388dd9e930b3f445"
      def install
        bin.install "bluectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.7/bluectl_linux_arm64.tar.gz"
      sha256 "29092bbbb15f5d0be0e5f71b1e8cb1a67bb18999bd86ca06b23fa0d34871e04b"
      def install
        bin.install "bluectl"
      end
    end
  end

  test do
    system "#{bin}/bluectl", "--help"
  end
end
