# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bluectl < Formula
  desc "CLI for managing BlueField DPUs via Project Cobalt"
  homepage "https://github.com/gobeyondidentity/cobalt"
  version "0.6.13"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gobeyondidentity/cobalt/releases/download/v0.6.13/bluectl_darwin_amd64.tar.gz"
      sha256 "66975245a2e5ed63fb87be7656f9bdddfca2373d6608eae498f501e611b3a036"

      def install
        bin.install "bluectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gobeyondidentity/cobalt/releases/download/v0.6.13/bluectl_darwin_arm64.tar.gz"
      sha256 "ae5db1842c11f73997d79dacfd00bea23943a25860988ceae103d7024c38cbce"

      def install
        bin.install "bluectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/cobalt/releases/download/v0.6.13/bluectl_linux_amd64.tar.gz"
      sha256 "a96da9ee816c451a9af877612b322004a3f0ea95d33af44413ae50df8002f1b1"
      def install
        bin.install "bluectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/cobalt/releases/download/v0.6.13/bluectl_linux_arm64.tar.gz"
      sha256 "381cd55b55f41eebd3ee4be29d2e848b982483e832a211002ad80c80933e4f59"
      def install
        bin.install "bluectl"
      end
    end
  end

  test do
    system "#{bin}/bluectl", "--help"
  end
end
