# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dpuemu < Formula
  desc "DPU emulator for Secure Infrastructure local development"
  homepage "https://github.com/gobeyondidentity/secure-infra"
  version "0.6.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.10/dpuemu_darwin_amd64.tar.gz"
      sha256 "f36fbb1fd6988625e0291edd08cb990054ca638dc20137c69cb5d6e10bb8e3e7"

      def install
        bin.install "dpuemu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.10/dpuemu_darwin_arm64.tar.gz"
      sha256 "bb833863337568b255ca42e3a3e6d4a43d72b22d7d0c0c648b370232846cccf7"

      def install
        bin.install "dpuemu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.10/dpuemu_linux_amd64.tar.gz"
      sha256 "fca01b7b73993bd0bd7d28438f7c7b629f2fd081aa8fa97c903c9e0cf09e52c4"
      def install
        bin.install "dpuemu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.10/dpuemu_linux_arm64.tar.gz"
      sha256 "126c080a8987173367d2fb5400310499128951f336bf4b7cf667ca7bbde034a9"
      def install
        bin.install "dpuemu"
      end
    end
  end

  test do
    system "#{bin}/dpuemu", "--help"
  end
end
