# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dpuemu < Formula
  desc "DPU emulator for Secure Infrastructure local development"
  homepage "https://github.com/gobeyondidentity/secure-infra"
  version "0.6.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.8/dpuemu_darwin_amd64.tar.gz"
      sha256 "d098f4d92d694ec38fce986c40974811bf82dc9625fe24006a14b74f019d13bf"

      def install
        bin.install "dpuemu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.8/dpuemu_darwin_arm64.tar.gz"
      sha256 "1088b2adaa84f2b3bda5c0c70dad0cde06301fd8ed1d1e5a54b3eebcd717806a"

      def install
        bin.install "dpuemu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.8/dpuemu_linux_amd64.tar.gz"
      sha256 "31e1aac4fa7ea5f018b56f74a65b275d8e40ce31475e427b5dc7996237027406"
      def install
        bin.install "dpuemu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.8/dpuemu_linux_arm64.tar.gz"
      sha256 "e76030ffbb04cf33acc4a1e3d909cfa735d21e5bc897af1fc06a152195723f6f"
      def install
        bin.install "dpuemu"
      end
    end
  end

  test do
    system "#{bin}/dpuemu", "--help"
  end
end
