# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ga < Formula
  desc "Queue messages to Claude agents in tmux windows without interrupting"
  homepage "https://github.com/nmelo/gasadd"
  version "0.8.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/gasadd/releases/download/v0.8.7/gasadd_darwin_amd64.tar.gz"
      sha256 "fad374f4a66507d4c86824fe293c6b43a06607442130135b86d43208d723e3f8"

      define_method(:install) do
        bin.install "ga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/gasadd/releases/download/v0.8.7/gasadd_darwin_arm64.tar.gz"
      sha256 "64ec5f10ae35a50c96c22a8eae3f5395c100a13f43c0c8151b22fd56968d374e"

      define_method(:install) do
        bin.install "ga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasadd/releases/download/v0.8.7/gasadd_linux_amd64.tar.gz"
      sha256 "85fcdf957a768e040e1c3fd538d9dab47c9e785a391fef8d56fb9a3649d5412d"
      define_method(:install) do
        bin.install "ga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasadd/releases/download/v0.8.7/gasadd_linux_arm64.tar.gz"
      sha256 "264b3d6fdc5c5aaff1325c48636dcb5854ae2bb2a4f4932afed0e47cf88244d2"
      define_method(:install) do
        bin.install "ga"
      end
    end
  end
end
