# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gasadd < Formula
  desc "Queue messages to Claude agents in tmux windows without interrupting"
  homepage "https://github.com/nmelo/gasadd"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/gasadd/releases/download/v0.5.1/gasadd_darwin_amd64.tar.gz"
      sha256 "accb44c916a64c446f9b9f6508f6ac102a4e8940e07aec05f00270162eec59df"

      define_method(:install) do
        bin.install "ga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/gasadd/releases/download/v0.5.1/gasadd_darwin_arm64.tar.gz"
      sha256 "1655bd014dac28b22636dfe0ae3097bccd2d4d42f7f18b67f7432bcb5dfee5f5"

      define_method(:install) do
        bin.install "ga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasadd/releases/download/v0.5.1/gasadd_linux_amd64.tar.gz"
      sha256 "4a705f1761e1011c89ae79cbdc9ac8a28e2955bd6c06ef9145990b84a9cfc44d"
      define_method(:install) do
        bin.install "ga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasadd/releases/download/v0.5.1/gasadd_linux_arm64.tar.gz"
      sha256 "f26b1fa018ae39e67f762b794485e581b93356626c340fa71e5ef223fb8a9cc6"
      define_method(:install) do
        bin.install "ga"
      end
    end
  end
end
