# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gasadd < Formula
  desc "Queue messages to Claude agents in tmux windows without interrupting"
  homepage "https://github.com/nmelo/gasadd"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/gasadd/releases/download/v0.3.0/gasadd_darwin_amd64.tar.gz"
      sha256 "bba762123f01d6469ed31fe039da9054c911c748e33b4a05f879a678a8af2568"

      def install
        bin.install "ga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/gasadd/releases/download/v0.3.0/gasadd_darwin_arm64.tar.gz"
      sha256 "c0551bfad9cc43cae9fdfaf735da5439501f5d4fc28a7c9b14870104476a18e2"

      def install
        bin.install "ga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasadd/releases/download/v0.3.0/gasadd_linux_amd64.tar.gz"
      sha256 "7ac5212a6f56192ab7bc54ddadaf99e465d79cbe9bf3f6f4d990f03ba1ab0a78"
      def install
        bin.install "ga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasadd/releases/download/v0.3.0/gasadd_linux_arm64.tar.gz"
      sha256 "88426a3e5c8a91e418daf547eca5f889f6bc967fe2f9d7e13330c4ef23afd435"
      def install
        bin.install "ga"
      end
    end
  end
end
