# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gasmail < Formula
  desc "Persistent agent-to-agent messaging using beads"
  homepage "https://github.com/nmelo/gasmail"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/gasmail/releases/download/v0.2.7/gasmail_darwin_amd64.tar.gz"
      sha256 "293a626024f615e60461a4eab0e0203262621e1132b862c9bca6832e805a2119"

      define_method(:install) do
        bin.install "gm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/gasmail/releases/download/v0.2.7/gasmail_darwin_arm64.tar.gz"
      sha256 "5d2aefdaad82e5f9214b8ea62928658b997715a54d09d8eb5005ec57a9e04fe7"

      define_method(:install) do
        bin.install "gm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasmail/releases/download/v0.2.7/gasmail_linux_amd64.tar.gz"
      sha256 "710c42d29f86079e0b2ab8603e747399970904e61730396207b2369544f5c03b"
      define_method(:install) do
        bin.install "gm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasmail/releases/download/v0.2.7/gasmail_linux_arm64.tar.gz"
      sha256 "9afb0306fcfc49279ccdcdb8868a3e558dbbd55454bfe75236738c0cc224f811"
      define_method(:install) do
        bin.install "gm"
      end
    end
  end
end
