# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gasnudge < Formula
  desc "Send nudge messages to Claude agents in tmux windows"
  homepage "https://github.com/nmelo/gasnudge"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.4.0/gasnudge_darwin_amd64.tar.gz"
      sha256 "a2f770a2e852ee1ddfdad5b1763975fde5ff460a2daede3759296a92fd8abf61"

      def install
        bin.install "gn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.4.0/gasnudge_darwin_arm64.tar.gz"
      sha256 "d2859a9db4eb81f911172cd04533b49eb6fb118d09ad4de04d1aa5b9b7e9fa57"

      def install
        bin.install "gn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.4.0/gasnudge_linux_amd64.tar.gz"
      sha256 "5c2e9f6751e3931e1ad17c956dd77da41194fec8215645521739cbcb7012032a"
      def install
        bin.install "gn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.4.0/gasnudge_linux_arm64.tar.gz"
      sha256 "ccc8c18d57e0cdbd8ecad8ef1d3072a67e01c8012d17a7524f9d412b1864d14e"
      def install
        bin.install "gn"
      end
    end
  end
end
