# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gasnudge < Formula
  desc "Send nudge messages to Claude agents in tmux windows"
  homepage "https://github.com/nmelo/gasnudge"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.6.0/gasnudge_darwin_amd64.tar.gz"
      sha256 "da9711f5c375665cce4736067a369b6fae9c86dae9d6589beed6729da82b9ced"

      def install
        bin.install "gn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.6.0/gasnudge_darwin_arm64.tar.gz"
      sha256 "f2d9fa227eed1f4d995a9cd44b4f50a546aeea32ba1d87b07339cde54c2fb4ab"

      def install
        bin.install "gn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.6.0/gasnudge_linux_amd64.tar.gz"
      sha256 "da5390d65f7696cdbd5521f6a4db36bc78ff2c312bfb9a3cbdac5bdc1d1ef185"
      def install
        bin.install "gn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.6.0/gasnudge_linux_arm64.tar.gz"
      sha256 "938db9f1092ca0c03355d3cb6e0cdb52d4b19b7bc1ba7f83826b7b9026c37089"
      def install
        bin.install "gn"
      end
    end
  end
end
