# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gasnudge < Formula
  desc "Send nudge messages to Claude agents in tmux windows"
  homepage "https://github.com/nmelo/gasnudge"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.5.0/gasnudge_darwin_amd64.tar.gz"
      sha256 "0429b179ca410fb62d1cc2775a4f3baf03c2b6d8e7c80be6673e8a174f739800"

      def install
        bin.install "gn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.5.0/gasnudge_darwin_arm64.tar.gz"
      sha256 "ad47e5e2d63bd189a7392b83b02413eab93f5b54b919874e7acfaaf6e9d9e6b5"

      def install
        bin.install "gn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.5.0/gasnudge_linux_amd64.tar.gz"
      sha256 "aad6cf8a320e80dddf8bf3407241440cf63cca18858c1376a48184ab28e593dd"
      def install
        bin.install "gn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.5.0/gasnudge_linux_arm64.tar.gz"
      sha256 "eec10ef8a4d03b51f5cf00542fb82155bc32ec73f807c40962c606e1f2cbebf4"
      def install
        bin.install "gn"
      end
    end
  end
end
