# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gaspeek < Formula
  desc "Capture output from Claude agents in tmux windows"
  homepage "https://github.com/nmelo/gaspeek"
  version "0.1.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/gaspeek/releases/download/v0.1.0/gaspeek_darwin_amd64.tar.gz"
      sha256 "09faf73cde4af107fcf0bfe9a7ce2a8d898cbd6a617af5b36d2e56aef92bff3c"

      def install
        bin.install "gp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/gaspeek/releases/download/v0.1.0/gaspeek_darwin_arm64.tar.gz"
      sha256 "3da8f87981b350b51616db891c3f3142f4f5b6c4c23bd345f8debf3bb4d65ab4"

      def install
        bin.install "gp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gaspeek/releases/download/v0.1.0/gaspeek_linux_amd64.tar.gz"
      sha256 "9695ab30b1add37d8403a66961169f5b8b20bbc00f089b7c3f8a1f9e4839d725"
      def install
        bin.install "gp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gaspeek/releases/download/v0.1.0/gaspeek_linux_arm64.tar.gz"
      sha256 "60f74c59916a89333823a8036c309caefdf2f3d7ad9171de0d3a477b5a73c25f"
      def install
        bin.install "gp"
      end
    end
  end

  test do
    assert_match "gp", shell_output("#{bin}/gp --help")
  end
end
