# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gaspeek < Formula
  desc "Read output from Claude agents in tmux windows"
  homepage "https://github.com/nmelo/gaspeek"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/gaspeek/releases/download/v0.1.5/gaspeek_darwin_amd64.tar.gz"
      sha256 "f202b59eb9d6a0615dc90e036e3d3ad11a31384a7f102ad5f3c9667504ee9034"

      define_method(:install) do
        bin.install "gp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/gaspeek/releases/download/v0.1.5/gaspeek_darwin_arm64.tar.gz"
      sha256 "ae7649733fc98ffbf4dd0783bb087cfdeced56bbdaafbb40e29ec480f855fad2"

      define_method(:install) do
        bin.install "gp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gaspeek/releases/download/v0.1.5/gaspeek_linux_amd64.tar.gz"
      sha256 "3d81de0b88c32404cd9cb84ce481104c77dd168c9b329009e93f5be4707e9354"
      define_method(:install) do
        bin.install "gp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gaspeek/releases/download/v0.1.5/gaspeek_linux_arm64.tar.gz"
      sha256 "56c0b9bd3d097198a8a06d580b132c082db80ce92e2dfaa7aef5aa755c1d5c6f"
      define_method(:install) do
        bin.install "gp"
      end
    end
  end
end
