# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gm < Formula
  desc "Persistent agent-to-agent messaging using beads"
  homepage "https://github.com/nmelo/gasmail"
  version "0.2.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/gasmail/releases/download/v0.2.9/gasmail_darwin_amd64.tar.gz"
      sha256 "90daf5a60626ddc344fb3099b722188cc496be4f11acd01987193b76f65f0e35"

      define_method(:install) do
        bin.install "gm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/gasmail/releases/download/v0.2.9/gasmail_darwin_arm64.tar.gz"
      sha256 "0676edb0af261955637a53683c774cf2383fc1bbc3ad27b52534ab058de401b0"

      define_method(:install) do
        bin.install "gm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasmail/releases/download/v0.2.9/gasmail_linux_amd64.tar.gz"
      sha256 "6e3fb972f4b3cd5f3a2a91bf7458f1c14e6000600f8638c72d8fc5c1f79ad993"
      define_method(:install) do
        bin.install "gm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasmail/releases/download/v0.2.9/gasmail_linux_arm64.tar.gz"
      sha256 "39e039b672c2c6fa0dc98f86b59f9ad3743370f22ef1a803b7078537638ac6cd"
      define_method(:install) do
        bin.install "gm"
      end
    end
  end
end
