# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gn < Formula
  desc "Send nudge messages to Claude agents in tmux windows"
  homepage "https://github.com/nmelo/gasnudge"
  version "0.6.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.6.4/gasnudge_darwin_amd64.tar.gz"
      sha256 "d1780b264ed5df1525bf0260710ea2ff0e82c8990504dd339e68e0c6dda58cb0"

      define_method(:install) do
        bin.install "gn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.6.4/gasnudge_darwin_arm64.tar.gz"
      sha256 "c530fdb76613665fb70139699293fac6b0bbe0c5b6eff710f34ffcf5215f46e5"

      define_method(:install) do
        bin.install "gn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.6.4/gasnudge_linux_amd64.tar.gz"
      sha256 "a6cebf824d5b4900beca5d5a7f0cba19cc4ee506aedc28be39a4ae8295fdde2f"
      define_method(:install) do
        bin.install "gn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gasnudge/releases/download/v0.6.4/gasnudge_linux_arm64.tar.gz"
      sha256 "34b998a3db96334f1e923a87bca352b1cb202e03324ebacf0a1926aa74e4a6f4"
      define_method(:install) do
        bin.install "gn"
      end
    end
  end
end
