# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gp < Formula
  desc "Read output from Claude agents in tmux windows"
  homepage "https://github.com/nmelo/gaspeek"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/gaspeek/releases/download/v0.1.7/gaspeek_darwin_amd64.tar.gz"
      sha256 "b66d1d9319a07ea543bf7ee2b0be4e43010ef060b5756cd82e07d8fb9106c9b3"

      define_method(:install) do
        bin.install "gp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/gaspeek/releases/download/v0.1.7/gaspeek_darwin_arm64.tar.gz"
      sha256 "5832e3a9e8b114d40f2abbfbacf46a9c2e8ff0e04b0ad16f56577bbf438fcfd6"

      define_method(:install) do
        bin.install "gp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gaspeek/releases/download/v0.1.7/gaspeek_linux_amd64.tar.gz"
      sha256 "56531d3b3821e3e9a87edb3abdddcbf0bc1202e78018f2f760b3b2b88b4e3022"
      define_method(:install) do
        bin.install "gp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/gaspeek/releases/download/v0.1.7/gaspeek_linux_arm64.tar.gz"
      sha256 "930e741cac301d177ecd495807cb1abac587c8d306d54d23005bea0907e82402"
      define_method(:install) do
        bin.install "gp"
      end
    end
  end
end
