# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Initech < Formula
  desc "Bootstrap and manage multi-agent development projects"
  homepage "https://github.com/nmelo/initech"
  version "0.10.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/initech/releases/download/v0.10.3/initech_darwin_amd64.tar.gz"
      sha256 "0e2770834ac9b769ad88adb43154437fc9141f07d217fb0ff539b7afdc29f59f"

      define_method(:install) do
        bin.install "initech"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/initech/releases/download/v0.10.3/initech_darwin_arm64.tar.gz"
      sha256 "4f5eebdff4d5e963b5fecf692c0a82f71bd3510d3f3397fd22c03b30204a568e"

      define_method(:install) do
        bin.install "initech"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/initech/releases/download/v0.10.3/initech_linux_amd64.tar.gz"
      sha256 "a3a1ab959160d67da681cbbbc69fc51a46b8bdd8320945e99b335b57ade54fc8"
      define_method(:install) do
        bin.install "initech"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/initech/releases/download/v0.10.3/initech_linux_arm64.tar.gz"
      sha256 "81182d3c25bf37a89c78b6684b06ffaa6e44a1a82cc2bb7a98dc0ad2589de21f"
      define_method(:install) do
        bin.install "initech"
      end
    end
  end

  test do
    system "#{bin}/initech", "version"
  end
end
