# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Initech < Formula
  desc "Bootstrap and manage multi-agent development projects"
  homepage "https://github.com/nmelo/initech"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nmelo/initech/releases/download/v0.9.0/initech_darwin_amd64.tar.gz"
      sha256 "a5a5994c6370a01006939bae5101156af0e3d7982f64c20851c18778e7255b2c"

      define_method(:install) do
        bin.install "initech"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nmelo/initech/releases/download/v0.9.0/initech_darwin_arm64.tar.gz"
      sha256 "f5b0294ee271d933b97c6788c1b9cd760f2811da44481c7be6e21972275c5669"

      define_method(:install) do
        bin.install "initech"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/initech/releases/download/v0.9.0/initech_linux_amd64.tar.gz"
      sha256 "da161cf0c80a0200bbad7e40880591580d167a607fc8f8da6257bab3f549fa05"
      define_method(:install) do
        bin.install "initech"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nmelo/initech/releases/download/v0.9.0/initech_linux_arm64.tar.gz"
      sha256 "3c79875334b53cf0f3748b246bf71a911e9af95640770906ce172c0f92b90b3d"
      define_method(:install) do
        bin.install "initech"
      end
    end
  end

  test do
    system "#{bin}/initech", "version"
  end
end
