# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Km < Formula
  desc "Key management CLI for Project Cobalt"
  homepage "https://github.com/gobeyondidentity/cobalt"
  version "0.6.14"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gobeyondidentity/cobalt/releases/download/v0.6.14/km_darwin_amd64.tar.gz"
      sha256 "7ce7d5487c37cc3fae8c75b06874c44e3a7404b296fcdd07cff93b280cbbeb91"

      def install
        bin.install "km"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gobeyondidentity/cobalt/releases/download/v0.6.14/km_darwin_arm64.tar.gz"
      sha256 "4247e86907707ff7b7d0dc4a9896057a135d20771aca17df181ef0be637b0a12"

      def install
        bin.install "km"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/cobalt/releases/download/v0.6.14/km_linux_amd64.tar.gz"
      sha256 "5ea6659f11880aab737fc0c5bf1bff499a843cedf81e4d7a5a13746aa000319c"
      def install
        bin.install "km"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/cobalt/releases/download/v0.6.14/km_linux_arm64.tar.gz"
      sha256 "37a8cc2fd56e25fcc2de3317b6e92ca44bc8ae774917d9dbf87d3336084456a3"
      def install
        bin.install "km"
      end
    end
  end

  test do
    system "#{bin}/km", "--help"
  end
end
