# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Km < Formula
  desc "Key management CLI for Secure Infrastructure"
  homepage "https://github.com/gobeyondidentity/secure-infra"
  version "0.6.6-rc1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.6-rc1/km_darwin_amd64.tar.gz"
      sha256 "5d6d9f0b9f7bad36a692b85985639cbf31170b5e577d85aa3aa12850cfb44d34"

      def install
        bin.install "km"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.6-rc1/km_darwin_arm64.tar.gz"
      sha256 "8f9743f4c11dff086a027802bd0961396d30c677e9c64745dbf15db193cf697f"

      def install
        bin.install "km"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.6-rc1/km_linux_amd64.tar.gz"
      sha256 "b8815a08f2fe6350c2ea4fbaa8418b0efcc5ab473070f09cc6982be6deb7755f"
      def install
        bin.install "km"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.6-rc1/km_linux_arm64.tar.gz"
      sha256 "28fe6ea6e925a8f4868a1ba1821b8eb205a7857e88c87d31c5c2402dcd76470d"
      def install
        bin.install "km"
      end
    end
  end

  test do
    system "#{bin}/km", "--help"
  end
end
