# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Km < Formula
  desc "Key management CLI for Secure Infrastructure"
  homepage "https://github.com/gobeyondidentity/secure-infra"
  version "0.6.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.8/km_darwin_amd64.tar.gz"
      sha256 "7bd0553e9202fb1536b62673a01dcd18fdf727516f43cd41a9a351d08e2ea502"

      def install
        bin.install "km"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.8/km_darwin_arm64.tar.gz"
      sha256 "abc8f3781e00b072a16aed666add756838664d51b9b4c4cb171d6c6592c14829"

      def install
        bin.install "km"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.8/km_linux_amd64.tar.gz"
      sha256 "028d78d3b75141f32667663b1b500c2954d3f31af3d194e837b113a95969fa67"
      def install
        bin.install "km"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.8/km_linux_arm64.tar.gz"
      sha256 "5853bd5726587021219300b77cbf492dad8777be7ab151a851d0dd8a698af878"
      def install
        bin.install "km"
      end
    end
  end

  test do
    system "#{bin}/km", "--help"
  end
end
