# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nexus < Formula
  desc "Nexus control plane for Secure Infrastructure"
  homepage "https://github.com/gobeyondidentity/secure-infra"
  version "0.6.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.3/control-plane_darwin_amd64.tar.gz"
      sha256 "de2ede8841bd0c19f38ddeacc745a6c36099281fe8bff027bcd70539401bfaf0"

      def install
        bin.install "control-plane" => "nexus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.3/control-plane_darwin_arm64.tar.gz"
      sha256 "75bbe03e5d52ce03eaf8b0196eb4e337fb88c11a1be15049e31c38ac24aab0bb"

      def install
        bin.install "control-plane" => "nexus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.3/control-plane_linux_amd64.tar.gz"
      sha256 "9fbb690a6964d9faf1a43e9220cb7cd9c8c089d26cc2ab093443ae0c2d0a7b90"
      def install
        bin.install "control-plane" => "nexus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/secure-infra/releases/download/v0.6.3/control-plane_linux_arm64.tar.gz"
      sha256 "829ae9190d01d6cd385940fb29b0e3dcd3bb207de2948d457d4967dc766180b6"
      def install
        bin.install "control-plane" => "nexus"
      end
    end
  end

  test do
    system "#{bin}/nexus", "--help"
  end
end
