# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sentry < Formula
  desc "Sentry host agent for Project Cobalt attestation"
  homepage "https://github.com/gobeyondidentity/cobalt"
  version "0.6.13"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gobeyondidentity/cobalt/releases/download/v0.6.13/sentry_darwin_amd64.tar.gz"
      sha256 "82f67be87bc7f9a8a5e72bd63015679eb7adb8423c652ce7cb274e3768d9e2e8"

      def install
        bin.install "sentry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gobeyondidentity/cobalt/releases/download/v0.6.13/sentry_darwin_arm64.tar.gz"
      sha256 "c7885c4e8aef225100a90a89b5dd91e7f803e9099bbb10ff7db30f0c1db070f2"

      def install
        bin.install "sentry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/cobalt/releases/download/v0.6.13/sentry_linux_amd64.tar.gz"
      sha256 "d4f08a4ff6de28337dfde2a4289ecf67e0309e89ebb42c13406ae24f59a3bfd1"
      def install
        bin.install "sentry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobeyondidentity/cobalt/releases/download/v0.6.13/sentry_linux_arm64.tar.gz"
      sha256 "5e65ac3fefa04133894953a64241eec9d11750c5784bbfc54a1e40491d264c55"
      def install
        bin.install "sentry"
      end
    end
  end

  test do
    system "#{bin}/sentry", "--help"
  end
end
